"use client"

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowRight } from "lucide-react"
import { useEffect } from "react"
import { useRouter } from "next/navigation"

export default function Home() {
  const token = localStorage.getItem("token")
  const router  = useRouter()
  useEffect(() => {
    if(token){
      router.push('/dashboard')
    }
    else{
      router.push('/')
    }
  },[])
  return (
    <div className="flex flex-col w-full">
      <header className="border-b w-full">
        <div className="px-10 flex h-16 items-center justify-between">
          <div className="flex items-center gap-2 font-semibold">
            <span className="text-xl">CareerPath</span>
          </div>
          <nav className="flex gap-4">
            <Link href="/login">
              <Button variant="ghost">Login</Button>
            </Link>
            <Link href="/register">
              <Button>Register</Button>
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1 w-full">
        <section className="py-24 md:py-32">
          <div className="px-10 grid gap-10 md:grid-cols-2 md:gap-16">
            <div className="flex flex-col justify-center space-y-6">
              <div className="space-y-2">
                <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                  Your Career Journey Starts Here
                </h1>
                <p className="text-lg text-muted-foreground md:text-xl">
                  Upload your resume and get personalized career roadmaps generated by AI.
                </p>
              </div>
              <div className="flex flex-col gap-2 sm:flex-row">
                <Link href="/register">
                  <Button size="lg" className="gap-2">
                    Get Started <ArrowRight size={16} />
                  </Button>
                </Link>
                <Link href="/login">
                  <Button size="lg" variant="outline">
                    Login
                  </Button>
                </Link>
              </div>
            </div>
            <div className="flex items-center justify-center">
              <div className="relative h-[350px] w-[350px] rounded-lg bg-muted p-4 md:h-[450px] md:w-[650px]">
                <div className="absolute inset-0 flex items-center justify-center">
                  <div className="space-y-4 p-6">
                    <div className="h-4 w-32 rounded bg-muted-foreground/20"></div>
                    <div className="h-4 w-48 rounded bg-muted-foreground/20"></div>
                    <div className="h-4 w-40 rounded bg-muted-foreground/20"></div>
                    <div className="h-4 w-36 rounded bg-muted-foreground/20"></div>
                    <div className="mt-8 space-y-3">
                      <div className="flex items-center gap-2">
                        <div className="h-6 w-6 rounded-full bg-primary/80"></div>
                        <div className="h-3 w-24 rounded bg-muted-foreground/20"></div>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="h-6 w-6 rounded-full bg-primary/60"></div>
                        <div className="h-3 w-28 rounded bg-muted-foreground/20"></div>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="h-6 w-6 rounded-full bg-primary/40"></div>
                        <div className="h-3 w-20 rounded bg-muted-foreground/20"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
